/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.EnterpriseAdmin;

import TheBusiness.Enterprise.Enterprise;
import TheBusiness.Organization.Organization;
import TheBusiness.Organization.ClinicOrganization;
import TheBusiness.Personnel.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author soham
 */
public class ManagePersonnel extends javax.swing.JPanel {

    private JPanel workContainer;
    private Enterprise enterprise;
    
    public ManagePersonnel(JPanel workContainer, Enterprise enterprise ) {
        initComponents();
        this.workContainer = workContainer;
        this.enterprise = enterprise;
        populateTable();
        
        
    }
    
    private void populateTable(){
        
        DefaultTableModel defaulttabelmodel = (DefaultTableModel) tblperson.getModel();
        
        defaulttabelmodel.setRowCount(0);
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList())
        {   
            for(Person person: organization.getPersonDirectory().getPeopleList())
            {
                Object[] row = new Object[5];
            row[0] = person;
            row[1] = person.getEmail();
            row[2] = person.getPhone();
            row[3] = person.getDateOfBirth();
            if(organization instanceof ClinicOrganization)
            {
                ClinicOrganization satOrg =(ClinicOrganization)organization;
                row[4] = satOrg.getClincName()+"Clinic";
            }
            else 
                row[4] = organization;
           
            
            defaulttabelmodel.addRow(row);
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblperson = new javax.swing.JTable();
        btnCreateNewPerson = new javax.swing.JButton();
        btnViewUpdatePerson = new javax.swing.JButton();
        btnRemovePerson = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(70, 130, 180));

        lblTitle.setFont(new java.awt.Font("October Compressed Devanagari", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Persons");

        tblperson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person Name", "email", "Phone Number", "Date of Birth", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblperson.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblperson);
        if (tblperson.getColumnModel().getColumnCount() > 0) {
            tblperson.getColumnModel().getColumn(0).setResizable(false);
            tblperson.getColumnModel().getColumn(1).setResizable(false);
            tblperson.getColumnModel().getColumn(2).setResizable(false);
            tblperson.getColumnModel().getColumn(3).setResizable(false);
            tblperson.getColumnModel().getColumn(4).setResizable(false);
        }

        btnCreateNewPerson.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateNewPerson.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnCreateNewPerson.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNewPerson.setText("Create New Person >>");
        btnCreateNewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewPersonActionPerformed(evt);
            }
        });

        btnViewUpdatePerson.setBackground(new java.awt.Color(0, 0, 0));
        btnViewUpdatePerson.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnViewUpdatePerson.setForeground(new java.awt.Color(255, 255, 255));
        btnViewUpdatePerson.setText("View / Update Person");
        btnViewUpdatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdatePersonActionPerformed(evt);
            }
        });

        btnRemovePerson.setBackground(new java.awt.Color(0, 0, 0));
        btnRemovePerson.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnRemovePerson.setForeground(new java.awt.Color(255, 255, 255));
        btnRemovePerson.setText("Remove Person");
        btnRemovePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePersonActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ICONS/11122021icons/MicrosoftTeams-image (2).png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(133, 133, 133))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnViewUpdatePerson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemovePerson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateNewPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateNewPerson)
                    .addComponent(btnViewUpdatePerson)
                    .addComponent(btnRemovePerson))
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemovePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePersonActionPerformed
        // TODO add your handling code here:
         int row = tblperson.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a Employee from table");
            return;
        }
        
        Person person = (Person)tblperson.getValueAt(row, 0);
        Organization org = (Organization) tblperson.getValueAt(row, 4);
        
        org.getPersonDirectory().removePerson(person);
        populateTable();
        
        
        
    }//GEN-LAST:event_btnRemovePersonActionPerformed

    private void btnCreateNewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewPersonActionPerformed
        // TODO add your handling code here:
        CreatePerson panel = new CreatePerson(workContainer, enterprise);
        workContainer.add("CreateEmployeeJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnCreateNewPersonActionPerformed

    private void btnViewUpdatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdatePersonActionPerformed
        // TODO add your handling code here:
        int row = tblperson.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a Employee from table");
            return;
        }
        Person person = (Person)tblperson.getValueAt(row, 0);
        Organization org = (Organization) tblperson.getValueAt(row, 4);
        
        
        
        UpdatePerson panel = new UpdatePerson(workContainer, person, org);
        workContainer.add("ViewPersonJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnViewUpdatePersonActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewPerson;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemovePerson;
    private javax.swing.JButton btnViewUpdatePerson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblperson;
    // End of variables declaration//GEN-END:variables
}
