/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.EnterpriseAdmin;

import TheBusiness.Ecosystems;
import TheBusiness.Enterprise.Enterprise;
import TheBusiness.Organization.Organization;
import TheBusiness.Organization.ClinicOrganization;
import TheBusiness.UserAccountManagement.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author soham
 */
public class ManageUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserAccount
     */
    private JPanel workContainer;
    private Enterprise enterprise;
    private Ecosystems business;
    
    public ManageUserAccount(JPanel workContainer, Enterprise enterprise , Ecosystems business) {
        initComponents();
        this.workContainer = workContainer;
        this.enterprise = enterprise;
        this.business = business;
        populateTable();
    }
    
    protected void populateTable(){
        DefaultTableModel defaulttabelmodel = (DefaultTableModel) tblaccts.getModel();

        defaulttabelmodel.setRowCount(0);
        
            for (UserAccount ua : enterprise.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[5];
                row[0] = ua.getPerson().getFirstName()+ " "+ua.getPerson().getLastName();
                row[1] = "Enterprise Admin";
                row[2] = ua;
                row[3] = ua.getPassword();
                row[4] = ua.getRole();
                
                ((DefaultTableModel) tblaccts.getModel()).addRow(row);
            }
        
        

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            for (UserAccount ua : organization.getUserAccountDirectory().getUserAccountList()) {
                Object row[] = new Object[5];
                row[0] = ua.getPerson().getFirstName()+ " "+ua.getPerson().getLastName();
                if(organization instanceof ClinicOrganization)
            {
                ClinicOrganization satOrg =(ClinicOrganization)organization;
                row[1] = satOrg.getClincName()+"Clinic";
            }
                else row[1] = organization;
                row[2] = ua;
                row[3] = ua.getPassword();
                row[4] = ua.getRole();
                
                ((DefaultTableModel) tblaccts.getModel()).addRow(row);
            }
        }
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblaccts = new javax.swing.JTable();
        btnCreateNewUserAccount = new javax.swing.JButton();
        btnViewUpdateUserAccount = new javax.swing.JButton();
        btnRemoveUser = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        setBackground(new java.awt.Color(70, 130, 180));

        lblTitle.setFont(new java.awt.Font("October Compressed Devanagari", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage User Accounts");

        tblaccts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person Name", "Department", "UserName", "Password", "Role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblaccts.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblaccts);
        if (tblaccts.getColumnModel().getColumnCount() > 0) {
            tblaccts.getColumnModel().getColumn(0).setResizable(false);
            tblaccts.getColumnModel().getColumn(1).setResizable(false);
            tblaccts.getColumnModel().getColumn(2).setResizable(false);
            tblaccts.getColumnModel().getColumn(3).setResizable(false);
            tblaccts.getColumnModel().getColumn(4).setResizable(false);
        }

        btnCreateNewUserAccount.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateNewUserAccount.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnCreateNewUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNewUserAccount.setText("Create New User Account >>");
        btnCreateNewUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewUserAccountActionPerformed(evt);
            }
        });

        btnViewUpdateUserAccount.setBackground(new java.awt.Color(0, 0, 0));
        btnViewUpdateUserAccount.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnViewUpdateUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnViewUpdateUserAccount.setText("View / Update User Account");
        btnViewUpdateUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdateUserAccountActionPerformed(evt);
            }
        });

        btnRemoveUser.setBackground(new java.awt.Color(0, 0, 0));
        btnRemoveUser.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnRemoveUser.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveUser.setText("Remove User");
        btnRemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnViewUpdateUserAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveUser, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateNewUserAccount)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateNewUserAccount)
                    .addComponent(btnViewUpdateUserAccount)
                    .addComponent(btnRemoveUser))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNewUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewUserAccountActionPerformed
        // TODO add your handling code here:
         CreateUserAccount panel = new CreateUserAccount(workContainer, enterprise , this, business);
        workContainer.add("CreateUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnCreateNewUserAccountActionPerformed

    private void btnRemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUserActionPerformed
        // TODO add your handling code here:
        int row = tblaccts.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a user account from table");
            return;
        }
        Organization org = null;
        
        UserAccount ua = (UserAccount)tblaccts.getValueAt(row, 2);
        
        
        if(tblaccts.getValueAt(row, 1) instanceof String)
        {
            enterprise.getUserAccountDirectory().removeUserAccount(ua);
        }
        else
        { org = (Organization) tblaccts.getValueAt(row, 1);
        
        org.getUserAccountDirectory().removeUserAccount(ua);
        }
        populateTable();
        
    }//GEN-LAST:event_btnRemoveUserActionPerformed

    private void btnViewUpdateUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdateUserAccountActionPerformed
        // TODO add your handling code here:
        int row = tblaccts.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a user account from table");
            return;
        }
        Organization org = null;
        UserAccount ua = (UserAccount)tblaccts.getValueAt(row, 2);
        if((tblaccts.getValueAt(row, 1) instanceof String) == false)
        org = (Organization) tblaccts.getValueAt(row, 1);
        UpdateUserAccount panel = new UpdateUserAccount(workContainer, enterprise , this, ua, org, business);
        workContainer.add("ViewUserAccountJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
        
    }//GEN-LAST:event_btnViewUpdateUserAccountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNewUserAccount;
    private javax.swing.JButton btnRemoveUser;
    private javax.swing.JButton btnViewUpdateUserAccount;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblaccts;
    // End of variables declaration//GEN-END:variables
}
