/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.Patient;

import TheBusiness.Ecosystems;
import TheBusiness.Enterprise.Enterprise;
import TheBusiness.Enterprise.HospitalEnterprise;
import TheBusiness.Organization.Organization;
import TheBusiness.UserAccountManagement.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Dsouza
 */
public class PatientDashboard1 extends javax.swing.JPanel {

    /**
     * Creates new form PatientDashboard1
     */
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private Organization organization;
    private Ecosystems business;
    
    public PatientDashboard1(JPanel userProcessContainer,UserAccount userAccount, Enterprise enterprise, Organization organization, Ecosystems business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = organization;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        workContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        lblMainMenu = new javax.swing.JLabel();
        btnViewAdministeredVaccines = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        workContainer.setBackground(new java.awt.Color(70, 130, 180));
        workContainer.setLayout(new java.awt.CardLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/patient.gif"))); // NOI18N
        workContainer.add(jLabel2, "card2");

        jSplitPane1.setRightComponent(workContainer);

        mainMenu.setBackground(new java.awt.Color(70, 130, 180));

        lblMainMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMainMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMainMenu.setText("Main Menu:");

        btnViewAdministeredVaccines.setBackground(new java.awt.Color(0, 0, 0));
        btnViewAdministeredVaccines.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewAdministeredVaccines.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAdministeredVaccines.setText("View Administered Vaccines");
        btnViewAdministeredVaccines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAdministeredVaccinesActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("PATIENT");

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewAdministeredVaccines, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainMenuLayout.createSequentialGroup()
                        .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMainMenu)
                            .addGroup(mainMenuLayout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(lblTitle)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblTitle)
                .addGap(54, 54, 54)
                .addComponent(lblMainMenu)
                .addGap(18, 18, 18)
                .addComponent(btnViewAdministeredVaccines)
                .addContainerGap(416, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(mainMenu);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewAdministeredVaccinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAdministeredVaccinesActionPerformed
        // TODO add your handling code here:
        VaccinatedPatients panel = new VaccinatedPatients(workContainer, (HospitalEnterprise)enterprise, userAccount);
        workContainer.add("AdministeredVaccineListJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnViewAdministeredVaccinesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewAdministeredVaccines;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblMainMenu;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel workContainer;
    // End of variables declaration//GEN-END:variables
}
