/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.Distributor;

import TheBusiness.Ecosystems;
import TheBusiness.NationalEnterprise.Distributor;
import TheBusiness.Organization.DistributorOrganization;
import TheBusiness.UserAccountManagement.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author soham
 */
public class DistributorEmplDashboard extends javax.swing.JPanel {

    /**
     * Creates new form DistributorEmplDashboard
     */
    private JPanel userProcessContainer;  
    private Distributor enterprise;
    private UserAccount userAccount;
    private DistributorOrganization distributorOrg;
    private Ecosystems business;
    public DistributorEmplDashboard(JPanel userProcessContainer,UserAccount userAccount,Distributor enterprise,DistributorOrganization distributorOrg,Ecosystems business ) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.distributorOrg = distributorOrg;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        workContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mainMenu = new javax.swing.JPanel();
        lblMainMenu = new javax.swing.JLabel();
        btnManageWarehouse = new javax.swing.JButton();
        btnManufactureShippedOrders = new javax.swing.JButton();
        btnProviderOrders = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(185);

        workContainer.setBackground(new java.awt.Color(102, 153, 255));
        workContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(70, 130, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ICONS/11122021icons/001.gif"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        workContainer.add(jPanel1, "card2");

        jSplitPane1.setRightComponent(workContainer);

        mainMenu.setBackground(new java.awt.Color(70, 130, 180));

        lblMainMenu.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        lblMainMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblMainMenu.setText("Main Menu:");

        btnManageWarehouse.setBackground(new java.awt.Color(0, 0, 0));
        btnManageWarehouse.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnManageWarehouse.setForeground(new java.awt.Color(255, 255, 255));
        btnManageWarehouse.setText("Manage Warehouse");
        btnManageWarehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageWarehouseActionPerformed(evt);
            }
        });

        btnManufactureShippedOrders.setBackground(new java.awt.Color(0, 0, 0));
        btnManufactureShippedOrders.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnManufactureShippedOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnManufactureShippedOrders.setText("Manufacture Shipped Orders");
        btnManufactureShippedOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManufactureShippedOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufactureShippedOrdersActionPerformed(evt);
            }
        });

        btnProviderOrders.setBackground(new java.awt.Color(0, 0, 0));
        btnProviderOrders.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnProviderOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnProviderOrders.setText("Provider Orders");
        btnProviderOrders.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProviderOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProviderOrdersActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("DISTRIBUTOR");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/distributor2_150x150.jpg"))); // NOI18N

        javax.swing.GroupLayout mainMenuLayout = new javax.swing.GroupLayout(mainMenu);
        mainMenu.setLayout(mainMenuLayout);
        mainMenuLayout.setHorizontalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnProviderOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageWarehouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManufactureShippedOrders, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(mainMenuLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTitle)
                                .addComponent(lblMainMenu))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainMenuLayout.setVerticalGroup(
            mainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainMenuLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle)
                .addGap(31, 31, 31)
                .addComponent(lblMainMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageWarehouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManufactureShippedOrders)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnProviderOrders)
                .addGap(33, 33, 33)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(mainMenu);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageWarehouseActionPerformed
        // TODO add your handling code here:
        WarehouseManagement panel = new WarehouseManagement(workContainer, enterprise, distributorOrg);
        workContainer.add("ManageWarehouseJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
        
        
        
    }//GEN-LAST:event_btnManageWarehouseActionPerformed

    private void btnManufactureShippedOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufactureShippedOrdersActionPerformed
        // TODO add your handling code here:
         OrderManagementFromManufacturer panel = new OrderManagementFromManufacturer(workContainer, enterprise, distributorOrg);
        workContainer.add("ManageOrdersfromManufacturerJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnManufactureShippedOrdersActionPerformed

    private void btnProviderOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProviderOrdersActionPerformed
        // TODO add your handling code here:
        ProviderOrdersManagement panel = new ProviderOrdersManagement(workContainer, enterprise, distributorOrg, userAccount, business);
        workContainer.add("ManageProviderOrdersJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnProviderOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageWarehouse;
    private javax.swing.JButton btnManufactureShippedOrders;
    private javax.swing.JButton btnProviderOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblMainMenu;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JPanel workContainer;
    // End of variables declaration//GEN-END:variables
}
