/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.Distributor;

import TheBusiness.Ecosystems;
import TheBusiness.Enterprise.Enterprise;
import TheBusiness.NationalEnterprise.Distributor;
import TheBusiness.Organization.DistributorOrganization;
import TheBusiness.Organization.Organization;
import TheBusiness.UserAccountManagement.UserAccount;
import TheBusiness.WorkOrderQueue.ProviderOrderRequest;
import TheBusiness.WorkOrderQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author soham
 */
public class ProviderOrdersManagement extends javax.swing.JPanel {


    
     private JPanel workContainer;  
    private Distributor enterprise;
    private UserAccount userAccount;
    private DistributorOrganization distributorOrg;
    private Ecosystems business;
    
    
    public ProviderOrdersManagement(JPanel workContainer,Distributor enterprise,DistributorOrganization distributorOrg, UserAccount userAccount,Ecosystems business) {
        initComponents();
         this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.distributorOrg = distributorOrg;
        this.business = business;
        this.workContainer = workContainer;
        populateContractTable();
        populateAdhocTable();
    }
    
    private void populateContractTable(){
        
        DefaultTableModel defaulttabelmodel = (DefaultTableModel) tblcont.getModel();
        defaulttabelmodel.setRowCount(0);
        
         DistributorOrganization distOrg = null;
         
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
        {   if(org instanceof DistributorOrganization)
        {   distOrg = (DistributorOrganization)org;
            for(WorkRequest workRequest : distOrg.getWorkQueue().getWorkRequestList())
            {   if(workRequest instanceof ProviderOrderRequest)
            {ProviderOrderRequest vaccineOrderWR = (ProviderOrderRequest)workRequest;
                if(vaccineOrderWR.isasReq()== false)
                {
                Object[] row = new Object[9];
            
                row[0] = vaccineOrderWR;
                row[1] = getContractDetails(vaccineOrderWR);
                row[2] = vaccineOrderWR.getEnterprise();
                row[3] = vaccineOrderWR.getreqState();
                row[4] = vaccineOrderWR.getSender();
                row[5] = vaccineOrderWR.getdeliDate();
                row[6] = vaccineOrderWR.getStatus();
                row[7] = vaccineOrderWR.getReceiver();
                row[8] = vaccineOrderWR.getResolveDate();               
                defaulttabelmodel.addRow(row);
                
                }
            }
            }
        }
        
        
        
        
    }
        
        
    }
    
    private void populateAdhocTable(){
        
        DefaultTableModel defaulttabelmodel = (DefaultTableModel) tblnormal.getModel();
        defaulttabelmodel.setRowCount(0);
        
         DistributorOrganization distOrg = null;
         
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
        {   if(org instanceof DistributorOrganization)
        {   distOrg = (DistributorOrganization)org;
            for(WorkRequest workRequest : distOrg.getWorkQueue().getWorkRequestList())
            {   if(workRequest instanceof ProviderOrderRequest)
            {ProviderOrderRequest vaccineOrderWR = (ProviderOrderRequest)workRequest;
                if(vaccineOrderWR.isasReq()== true)
                {
                Object[] row = new Object[7];
            
                row[0] = vaccineOrderWR;
                row[1] = vaccineOrderWR.getEnterprise();
                row[2] = vaccineOrderWR.getreqState();
                row[3] = vaccineOrderWR.getSender();
                row[4] = vaccineOrderWR.getStatus();
                row[5] = vaccineOrderWR.getReceiver();
                row[6] = vaccineOrderWR.getResolveDate();
                
                
                defaulttabelmodel.addRow(row);
                
                }
            }
            }
        }
  
    }
 
    }
    
    
    private String getContractDetails(ProviderOrderRequest request){
        
        if(request.ishalfmonthContract())
            return "Half Monthly";
        else if(request.isfullMonthContract())
            return "Monthly";
        else
           return "As Required";
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcont = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        lblOrderType = new javax.swing.JLabel();
        btnViewDetailsAndShip = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblnormal = new javax.swing.JTable();
        lblAsRequiredOrders = new javax.swing.JLabel();
        btnRefresh1 = new javax.swing.JButton();
        btnViewDetailsAndShip1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(70, 130, 180));

        lblTitle.setFont(new java.awt.Font("October Compressed Devanagari", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Provider Orders");

        tblcont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Contract Type", "Provider", "State", "Sender", "Next Delivery Date", "Status", "Shipped by", "Last Shipping Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblcont.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblcont);

        btnRefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/MicrosoftTeams-image (2).png"))); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        lblOrderType.setFont(new java.awt.Font("October Compressed Devanagari", 1, 14)); // NOI18N
        lblOrderType.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderType.setText("Orders type:");

        btnViewDetailsAndShip.setBackground(new java.awt.Color(0, 0, 0));
        btnViewDetailsAndShip.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnViewDetailsAndShip.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetailsAndShip.setText("View Details and Ship");
        btnViewDetailsAndShip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewDetailsAndShip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsAndShipActionPerformed(evt);
            }
        });

        tblnormal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Provider", "State", "Sender", "Status", "Shipped By", "Shipping Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblnormal.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblnormal);

        lblAsRequiredOrders.setFont(new java.awt.Font("October Compressed Devanagari", 1, 14)); // NOI18N
        lblAsRequiredOrders.setForeground(new java.awt.Color(255, 255, 255));
        lblAsRequiredOrders.setText("AsRequired Orders:");

        btnRefresh1.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh1.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnRefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/MicrosoftTeams-image (2).png"))); // NOI18N
        btnRefresh1.setText("Refresh");
        btnRefresh1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });

        btnViewDetailsAndShip1.setBackground(new java.awt.Color(0, 0, 0));
        btnViewDetailsAndShip1.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnViewDetailsAndShip1.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetailsAndShip1.setText("View Details and Ship >>");
        btnViewDetailsAndShip1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewDetailsAndShip1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsAndShip1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblAsRequiredOrders)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh1)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewDetailsAndShip, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewDetailsAndShip1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblOrderType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRefresh)
                    .addComponent(lblOrderType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewDetailsAndShip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAsRequiredOrders)
                    .addComponent(btnRefresh1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewDetailsAndShip1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateContractTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnViewDetailsAndShipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsAndShipActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblcont.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Kindly select an Order from table");
            return;
        }

        ProviderOrderRequest request = (ProviderOrderRequest)tblcont.getValueAt(selectedRow, 0);

        ContractAndShipDetails panel = new ContractAndShipDetails(workContainer, userAccount, business, request, enterprise);
        workContainer.add("ViewContractDetailsAndShipJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnViewDetailsAndShipActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        populateContractTable();
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void btnViewDetailsAndShip1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsAndShip1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblnormal.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Kindly select an Order from table");
            return;
        }

        ProviderOrderRequest request = (ProviderOrderRequest)tblnormal.getValueAt(selectedRow, 0);

        AsRequestedAndShipDetails panel = new AsRequestedAndShipDetails(workContainer, userAccount, business, request, enterprise);
        workContainer.add("ViewAdhocDetailsAndShipJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
    }//GEN-LAST:event_btnViewDetailsAndShip1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnViewDetailsAndShip;
    private javax.swing.JButton btnViewDetailsAndShip1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAsRequiredOrders;
    private javax.swing.JLabel lblOrderType;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblcont;
    private javax.swing.JTable tblnormal;
    // End of variables declaration//GEN-END:variables
}
