/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.Distributor;

import TheBusiness.Enterprise.Enterprise;
import TheBusiness.Organization.DistributorOrganization;
import TheBusiness.Organization.ManufactureOrganization;
import TheBusiness.VaccineManagement.VaccineDetails;
import TheBusiness.WarehouseManagement.Warehouse;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author soham
 */
public class WarehouseManagement extends javax.swing.JPanel {

   
    private JPanel workContainer;
    private Enterprise enterprise;
    private DistributorOrganization distributorOrganization;
    
    
    public WarehouseManagement(JPanel workContainer,Enterprise enterprise, DistributorOrganization distributorOrganization ) {
        initComponents();
        this.workContainer = workContainer;
        this.enterprise = enterprise;
        this.distributorOrganization = distributorOrganization;
        populateTable();
    }
    
    
    private void populateTable(){
        
        DefaultTableModel defaulttabelmodel = (DefaultTableModel) tblware.getModel();
        defaulttabelmodel.setRowCount(0);
        
        for(Warehouse warehouse : distributorOrganization.getWarehouseDir().getWarehouseList())
        {
            Object[] row = new Object[3];
            row[0] = warehouse;
            row[1] = warehouse.getLocation();
            row[2] = calculateTotalVaccines(warehouse);
            defaulttabelmodel.addRow(row);
        }
   
        
    }
    
    
    private int calculateTotalVaccines(Warehouse warehouse){
        
        int totalVaccines = 0;
        for(VaccineDetails product : warehouse.getVaccineInventoryList())
        {   
            totalVaccines = totalVaccines + product.getAvailablity();
            
        }
        return totalVaccines;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblware = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lblAddNewWarehouse = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        btnAddWarehouse = new javax.swing.JButton();
        btnViewInventory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(70, 130, 180));

        lblTitle.setFont(new java.awt.Font("October Compressed Devanagari", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Manage Warehouses");

        tblware.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Location", "Total Vaccines"
            }
        ));
        tblware.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblware);

        lblAddNewWarehouse.setFont(new java.awt.Font("October Compressed Devanagari", 1, 14)); // NOI18N
        lblAddNewWarehouse.setForeground(new java.awt.Color(255, 255, 255));
        lblAddNewWarehouse.setText("Add New Warehouse:");

        lblLocation.setFont(new java.awt.Font("October Compressed Devanagari", 0, 14)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblLocation.setText("Location:");

        btnAddWarehouse.setBackground(new java.awt.Color(0, 0, 0));
        btnAddWarehouse.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnAddWarehouse.setForeground(new java.awt.Color(255, 255, 255));
        btnAddWarehouse.setText("Add Warehouse");
        btnAddWarehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddWarehouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddWarehouseActionPerformed(evt);
            }
        });

        btnViewInventory.setBackground(new java.awt.Color(0, 0, 0));
        btnViewInventory.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnViewInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnViewInventory.setText("View Inventory");
        btnViewInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInventoryActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/ware1.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddWarehouse, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(txtLocation)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnViewInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAddNewWarehouse))))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewInventory)
                .addGap(10, 10, 10)
                .addComponent(lblAddNewWarehouse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocation)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAddWarehouse))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddWarehouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddWarehouseActionPerformed
        // TODO add your handling code here:
        
        String location = txtLocation.getText();     
        Warehouse warehouse = distributorOrganization.getWarehouseDir().addNewWareHouse();
        warehouse.setLocation(location);
        populateTable();
        
    }//GEN-LAST:event_btnAddWarehouseActionPerformed

    private void btnViewInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInventoryActionPerformed
        // TODO add your handling code here:
        
          int selectedRow = tblware.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Kindly select a Warehouse from table");
            return;
        }
        
        Warehouse warehouse = (Warehouse)tblware.getValueAt(selectedRow, 0);
        
        ViewInventoryDistributor panel = new ViewInventoryDistributor(workContainer, warehouse);
        workContainer.add("ViewInventoryJPanel", panel);
        CardLayout layout = (CardLayout)workContainer.getLayout();
        layout.next(workContainer);
        
        
    }//GEN-LAST:event_btnViewInventoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddWarehouse;
    private javax.swing.JButton btnViewInventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddNewWarehouse;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblware;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
}
