/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.SystemAdmin;

import TheBusiness.Ecosystems;
import TheBusiness.Disease.Disease;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author soham
 */
public class AddDiseases extends javax.swing.JPanel {

    /**
     * Creates new form AddDiseases
     */
    private JPanel workContainer;
    private Ecosystems business;
    
    public AddDiseases(JPanel workContainer, Ecosystems business) {
        initComponents();
        this.workContainer = workContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dcldate = new com.toedter.calendar.JDateChooser();
        lblLastUpdateOn = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtDiseaseName = new javax.swing.JTextField();
        btnAddDiseaseInfo = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblCode = new javax.swing.JLabel();
        lblDiseaseName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(70, 130, 180));

        dcldate.setDateFormatString(" MMM, d yyyy");

        lblLastUpdateOn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLastUpdateOn.setForeground(new java.awt.Color(255, 255, 255));
        lblLastUpdateOn.setText("Last Updated on:");

        btnAddDiseaseInfo.setBackground(new java.awt.Color(0, 0, 0));
        btnAddDiseaseInfo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddDiseaseInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnAddDiseaseInfo.setText("Add Disease Info");
        btnAddDiseaseInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiseaseInfoActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("October Compressed Devanagari", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add New Disease Information");

        lblCode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCode.setForeground(new java.awt.Color(255, 255, 255));
        lblCode.setText("Code:");

        lblDiseaseName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDiseaseName.setForeground(new java.awt.Color(255, 255, 255));
        lblDiseaseName.setText("Disease Name:");

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ICONS/11122021icons/MicrosoftTeams-image (1).png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ICONS/11122021icons/dis1.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblDiseaseName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDiseaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCode)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnAddDiseaseInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLastUpdateOn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dcldate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBack))
                        .addGap(0, 431, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCode)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiseaseName)
                    .addComponent(txtDiseaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastUpdateOn)
                    .addComponent(dcldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddDiseaseInfo)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDiseaseInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiseaseInfoActionPerformed
        // TODO add your handling code here:
        String diseaseCode = txtCode.getText();
        if(diseaseCode.trim().equalsIgnoreCase(""))
        {JOptionPane.showMessageDialog(null, "Please enter a disease Code");
            return;
            
        }
        String diseaseName = txtDiseaseName.getText();
        if(diseaseName.trim().equalsIgnoreCase(""))
        {JOptionPane.showMessageDialog(null, "Please enter a disease Name");
            return;
            
        }
        
        Date lastUpdatedDate = dcldate.getDate();
        
        for(Disease d : business.getDiseaseDirectory().getdiseaseDirectory())
        {
            if(d.getDiseaseCode().equalsIgnoreCase(diseaseCode) && d.getDiseaseName().equalsIgnoreCase(diseaseName))
            {
                JOptionPane.showMessageDialog(null, "Disease exists!");
            return;
            }
        }

        Disease disease = business.getDiseaseDirectory().addNewDisease();
        disease.setDiseaseCode(diseaseCode);
        disease.setDiseaseName(diseaseName);
        disease.setLastUpdatedTime(lastUpdatedDate);
       

    }//GEN-LAST:event_btnAddDiseaseInfoActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDiseaseInfo;
    private javax.swing.JButton btnBack;
    private com.toedter.calendar.JDateChooser dcldate;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCode;
    private javax.swing.JLabel lblDiseaseName;
    private javax.swing.JLabel lblLastUpdateOn;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtDiseaseName;
    // End of variables declaration//GEN-END:variables
}
