/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.Manufacture;

import TheBusiness.Ecosystems;
import TheBusiness.NationalEnterprise.Manufacturer;
import TheBusiness.Organization.ManufactureOrganization;
import TheBusiness.Organization.Organization;
import TheBusiness.VaccineManagement.Vaccine;
import TheBusiness.VaccineManagement.VaccineDetails;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Dsouza
 */
public class AddVaccine extends javax.swing.JPanel {

    /**
     * Creates new form AddVaccine
     */
    private JPanel workContainer;
    private Manufacturer manufacturer;
    private Ecosystems business;
    
    public AddVaccine(JPanel workContainer, Manufacturer manufacturer, Ecosystems business) {
        initComponents();
        this.workContainer = workContainer;
        this.manufacturer = manufacturer;
        this.business = business;
        populateDepartmentJComboBox();
        populateVaccineJComboBox();
        
        
    }
    
    private void populateDepartmentJComboBox(){
        
        cbdeptlist.removeAllItems();
        
        for(Organization org: manufacturer.getOrganizationDirectory().getOrganizationList())
            cbdeptlist.addItem(org);
        
        
    }
    
    private void populateVaccineJComboBox(){
        
        cbvacclist.removeAllItems();
        
        for(Vaccine vaccine: business.getVaccineDirectory().getVaccineCatalog())
            cbvacclist.addItem(vaccine);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblVaccineName = new javax.swing.JLabel();
        cbvacclist = new javax.swing.JComboBox();
        lblLotNumber = new javax.swing.JLabel();
        txtLotNumber = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblVials = new javax.swing.JLabel();
        lblManufacturerDate = new javax.swing.JLabel();
        dcmanudate = new com.toedter.calendar.JDateChooser();
        btnAddNewVaccine = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblDepartment = new javax.swing.JLabel();
        cbdeptlist = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(37, 161, 142));

        lblTitle.setFont(new java.awt.Font("October Compressed Devanagari", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Add New Vaccine");

        lblVaccineName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVaccineName.setForeground(new java.awt.Color(255, 255, 255));
        lblVaccineName.setText("Vaccine Name:");

        cbvacclist.setForeground(new java.awt.Color(0, 0, 102));
        cbvacclist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblLotNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblLotNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblLotNumber.setText("Lot Number:");

        lblPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(255, 255, 255));
        lblPrice.setText("Price:");

        lblQuantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblQuantity.setText("Quantity:");

        lblVials.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblVials.setForeground(new java.awt.Color(255, 255, 255));
        lblVials.setText("Vials");

        lblManufacturerDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblManufacturerDate.setForeground(new java.awt.Color(255, 255, 255));
        lblManufacturerDate.setText("Manufacture Date:");

        btnAddNewVaccine.setBackground(new java.awt.Color(0, 0, 0));
        btnAddNewVaccine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAddNewVaccine.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewVaccine.setText("Add New Vaccine");
        btnAddNewVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewVaccineActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/MicrosoftTeams-image (1).png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDepartment.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDepartment.setForeground(new java.awt.Color(255, 255, 255));
        lblDepartment.setText("Department:");

        cbdeptlist.setForeground(new java.awt.Color(0, 0, 102));
        cbdeptlist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(lblDepartment)
                                .addGap(18, 18, 18)
                                .addComponent(cbdeptlist, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(btnBack))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPrice)
                                    .addComponent(lblLotNumber)
                                    .addComponent(lblVaccineName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtLotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbvacclist, 0, 149, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblQuantity)
                                    .addComponent(lblManufacturerDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddNewVaccine, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblVials))
                                    .addComponent(dcmanudate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 241, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDepartment)
                    .addComponent(cbdeptlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbvacclist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVaccineName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLotNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLotNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrice))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVials))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblManufacturerDate)
                    .addComponent(dcmanudate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnAddNewVaccine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddNewVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewVaccineActionPerformed
        // TODO add your handling code here:
        try{
        ManufactureOrganization manuOrg = (ManufactureOrganization)cbdeptlist.getSelectedItem();
        Vaccine vaccineDef = (Vaccine)cbvacclist.getSelectedItem();
        String lotNumber = txtLotNumber.getText();
        if(lotNumber.trim().equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Please enter Lot Number");
            return;
        }
        Double price = Double.parseDouble(txtPrice.getText());
        int quantity = Integer.parseInt(txtQuantity.getText());
        Date manufactureDate = dcmanudate.getDate();
        
        
        VaccineDetails product = manuOrg.getVaccineProductCatalog().addNewVaccineProduct();
        product.setVaccineDefinition(vaccineDef);
        product.setAvailablity(quantity);
        product.setBatchId(lotNumber);
        product.setManufactureDate(manufactureDate);
        product.setAvailablity(quantity);
        product.setVaccinePrice(price);
        product.setManufacturerName(manufacturer.getName());
        
        JOptionPane.showMessageDialog(null, "Vaccine Added!");
        
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, "Please enter numeric values for numeric fields");
            return;
        }
        
        
    }//GEN-LAST:event_btnAddNewVaccineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewVaccine;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox cbdeptlist;
    private javax.swing.JComboBox cbvacclist;
    private com.toedter.calendar.JDateChooser dcmanudate;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblLotNumber;
    private javax.swing.JLabel lblManufacturerDate;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVaccineName;
    private javax.swing.JLabel lblVials;
    private javax.swing.JTextField txtLotNumber;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
