/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Manufacture;

import TheBusiness.Ecosystems;
import TheBusiness.NationalEnterprise.Manufacturer;
import TheBusiness.OrderManagement.OrderItem;
import TheBusiness.Organization.DistributorOrganization;
import TheBusiness.Organization.ManufactureOrganization;
import TheBusiness.Organization.Organization;
import TheBusiness.VaccineManagement.VaccineDetails;
import TheBusiness.WorkOrderQueue.OrderVaccineWorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dsouza
 */
public class OrderProcessing extends javax.swing.JPanel {

    /**
     * Creates new form OrderProcessing
     */
    private JPanel workContainer;
    private OrderVaccineWorkRequest vaccineWorkRequest;
    private Manufacturer manufacturer;
    private Ecosystems business;

    public OrderProcessing(JPanel workContainer, OrderVaccineWorkRequest vaccineWorkRequest, Manufacturer manufacturer, Ecosystems business) {
        initComponents();
        this.workContainer = workContainer;
        this.vaccineWorkRequest = vaccineWorkRequest;
        this.manufacturer = manufacturer;
        this.business = business;
        txtOrderNumber.setText(String.valueOf(vaccineWorkRequest.getVaccineOrder().getOrderNumber()));
        populateTable();
        calculateTotalAmount();

    }

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tbldetails.getModel();

        model.setRowCount(0);

        for (OrderItem orderItem : vaccineWorkRequest.getVaccineOrder().getItemList()) {
            Object[] row = new Object[4];
            row[0] = orderItem.getVaccineDetails().getVaccineDefinition().getVaccineCode();
            row[1] = orderItem.getVaccineDetails().getVaccineDefinition().getVaccineName();
            row[2] = orderItem.getQuantity();
            row[3] = orderItem.getVaccineDetails().getVaccinePrice() * orderItem.getQuantity();

            model.addRow(row);
        }
    }

    private void calculateTotalAmount() {

        double totalAmount = 0;
        for (OrderItem orderItem : vaccineWorkRequest.getVaccineOrder().getItemList()) {
            totalAmount = totalAmount + (orderItem.getVaccineDetails().getVaccinePrice() * orderItem.getQuantity());
        }

        txtTotalAmountOfOrder.setText(String.valueOf(totalAmount));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbldetails = new javax.swing.JTable();
        lblOrderNumber = new javax.swing.JLabel();
        txtOrderNumber = new javax.swing.JTextField();
        lblTotalAmountOfOrder = new javax.swing.JLabel();
        txtTotalAmountOfOrder = new javax.swing.JTextField();
        btnShipOrder = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(37, 161, 142));

        lblTitle.setFont(new java.awt.Font("October Compressed Devanagari", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Process Orders");

        lblDetails.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblDetails.setText("Details:");

        tbldetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vaccine Code", "Vaccine Name", "Quantity", "Total Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbldetails.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbldetails);
        if (tbldetails.getColumnModel().getColumnCount() > 0) {
            tbldetails.getColumnModel().getColumn(2).setResizable(false);
            tbldetails.getColumnModel().getColumn(3).setResizable(false);
        }

        lblOrderNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblOrderNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderNumber.setText("Order Number:");

        txtOrderNumber.setEnabled(false);

        lblTotalAmountOfOrder.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTotalAmountOfOrder.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalAmountOfOrder.setText("Total Amount of Order: ");

        txtTotalAmountOfOrder.setEnabled(false);

        btnShipOrder.setBackground(new java.awt.Color(0, 0, 0));
        btnShipOrder.setFont(new java.awt.Font("October Compressed Devanagari", 1, 18)); // NOI18N
        btnShipOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnShipOrder.setText("Ship Order");
        btnShipOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShipOrderActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/ICONS/11122021icons/MicrosoftTeams-image (1).png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/ICONS/11122021icons/process.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1002, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnShipOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetails)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblOrderNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalAmountOfOrder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotalAmountOfOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBack))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderNumber)
                    .addComponent(txtOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblDetails)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalAmountOfOrder)
                    .addComponent(txtTotalAmountOfOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShipOrder)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workContainer.remove(this);
        CardLayout layout = (CardLayout) workContainer.getLayout();
        layout.previous(workContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnShipOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShipOrderActionPerformed
        // TODO add your handling code here:
        if(vaccineWorkRequest.getStatus().equalsIgnoreCase("Shipped") || vaccineWorkRequest.getStatus().equalsIgnoreCase("Stored"))
         {
             JOptionPane.showMessageDialog(null, "Order already shipped!");
             return;
         }
        
        vaccineWorkRequest.setStatus("Shipped");
        vaccineWorkRequest.setShipdate(new Date());

        DistributorOrganization distributorOrg = null;
            for (Organization org : business.getDistributor().getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof DistributorOrganization){
                    distributorOrg = (DistributorOrganization) org;
                    distributorOrg.getWorkQueue().addWorkRequest(vaccineWorkRequest);
                }
            }
            
            JOptionPane.showMessageDialog(null, "Order Sent to Distributor");

    }//GEN-LAST:event_btnShipOrderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnShipOrder;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblOrderNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalAmountOfOrder;
    private javax.swing.JTable tbldetails;
    private javax.swing.JTextField txtOrderNumber;
    private javax.swing.JTextField txtTotalAmountOfOrder;
    // End of variables declaration//GEN-END:variables
}
